### ISSUE TITLE
add freedom

### ISSUE THREAD

**Issue by jamiefjdiscord** [alejandroatacho/osu-KawataFuquila-CheatList#2]
u know what to do.

**Comment by LewdAleks** [comment]
when loki gives us the ok that its "allowed" ill add it since none of use have used it before.

**Comment by LewdAleks** [comment]
hi following up on this, we are not allowing freedom (the cheat) at this time for a few undisclosed reasons this will not be added for now

**Comment by LewdAleks** [comment]
hi following up on this, we are not allowing freedom (the cheat) at this time for a few undiscloed reasons
